### ISSUE TITLE
Customise BUILD_LIBRARY_FOR_DISTRIBUTION

### ISSUE THREAD

**Issue by dcacenabes** [bielikb/fastlane-plugin-create_xcframework#10]
Hi @bielikb ! 

We are using the plugin and it is working good. Thanks for that! For our use case, though, we would like to be able to disable BUILD_LIBRARY_FOR_DISTRIBUTION, but we have found that the plugin is replacing the configuration.
https://github.com/bielikb/fastlane-plugin-create_xcframework/blob/328af1ca322ab81db2273954aef94b1efbefd4f7/lib/fastlane/plugin/create_xcframework/actions/create_xcframework_action.rb#L137

We would like to contribute to the plugin and make it configurable (by default override it to keep current behavior, but give the possibility to the consumer of the plugin to specify whichever value they want for it). I wanted to know if you would be interested in including this in the plugin. If so, I will create a PR bringing in those changes.

Let me know your thoughts!

**Comment by bielikb** [comment]
Hi @dcacenabes, 

feel free to suggest the change via opening new PR ;)

In general, `BUILD_LIBRARY_FOR_DISTRIBUTION` flag turns on the module stability in Swift frameworks. Could you please explain the intent in what use-cases you want to build frameworks without the module stability?

Thanks in advance!

Best,
Boris

**Comment by dcacenabes** [comment]
Hi @bielikb,

Thanks for your quick reply! I am just realising that we were missing part of the big picture. For sure we need module stability, what we wanted to disable was library evolution. I just realised both are controlled at the same time.

Our use case is the following:

We are distributing internally an XCFramework that has a 3rd party dependency.
When we build the main app including that module, we also want to build the 3rd party dependency with BUILD_LIBRARY_FOR_DISTRIBUTION enabled. Currently that 3rd party is causing a segmentation fault if we try to build it with that flag enabled, so we were evaluating disabling it altogether, but we were not aware that it would also drop module stability.

**Comment by bielikb** [comment]
Hi @dcacenabes,

thanks for the context! If that 3rd party dependency is public OSS project, could you please point me towards it? Feel free to also share the crashlog or any other context. 
I'd be keen to analyse the issue to better understand/reason about the possibilities here.

Thanks.

Best,
Boris

**Comment by dcacenabes** [comment]
Hi @bielikb ,
We have 2 issues here, both with OSS projects, but both related with XCFrameworks and BUILD_LIBRARY_FOR_DISTRIBUTION. All of our modules are built with built for distribution enabled using your plugin.

### Symbol not found
Another of our XCFrameworks has [Device](https://github.com/Ekhoo/Device) as a 3rd party dependency. When we build the main app **without** BUILD_LIBRARY_FOR_DISTRIBUTION enabled, we get a crash at runtime related to this library and some symbols not found (because the compiler mangles the names)
```
dyld: Symbol not found: _$s6Device4SizeO11screen4InchyA2CmFWC
 Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/8959BED9-4316-4CD1-AE7A-3672C00832FA/data/Containers/Bundle/Application/73D8F218-D8B9-49CE-8BF9-D3C5586F3496/XXX.app/Frameworks/XXXCore.framework/XXXCore
 Expected in: /Users/xxx/Library/Developer/CoreSimulator/Devices/8959BED9-4316-4CD1-AE7A-3672C00832FA/data/Containers/Bundle/Application/73D8F218-D8B9-49CE-8BF9-D3C5586F3496/XXX.app/Frameworks/Device.framework/Device
```
So when building the main app we must enable also build library for distribution for the symbol names to match.

### Crashing the swift compiler
One of our internal XCFrameworks has as a dependency [Bond](https://github.com/DeclarativeHub/Bond).
I reported an [issue in their repo](https://github.com/DeclarativeHub/Bond/issues/705) and also to [Swift Bugs page](https://bugs.swift.org/browse/SR-14541). The latest is the one that has more details.
The segmentation fault in the compiler only happens with Xcode 12.5 (Swift 5.4) and BUILD_LIBRARY_FOR_DISTRIBUTION turned on.

**Comment by bielikb** [comment]
Thanks for the thorough walkthrough!

Ill try to repro the issues mentioned during the weekend. I cant promise anything atm, but Im eager to at least try to find solution.

**Comment by dcacenabes** [comment]
Hi @bielikb , I finally got some time to resume working on this, and [opened a pull request](https://github.com/bielikb/fastlane-plugin-create_xcframework/pull/12) that allows us to disable the overriding of the xcargs. Let me know your thoughts!

**Comment by dcacenabes** [comment]
PR was already merged
