### ISSUE TITLE
dSYMs and BCSymbolMaps are placed outside of xcframework

### ISSUE THREAD

**Issue by gdetari** [bielikb/fastlane-plugin-create_xcframework#8]
I am using this plugin as follows:
```
create_xcframework(
	workspace: 'Framework.xcworkspace',
	scheme: 'Framework',
	destinations: ['iOS'],
	xcframework_output_directory: 'output'
)
```

This results in having a separate Framework.xcframework, Framework.dSYMs and Framework.BCSymbolMaps

I would expect the symbols included inside the xcframework, next to the frameworks for the separate architectures.

**Comment by bielikb** [comment]
Hi @gdetari,

thanks for opening this issue. 

Can you please test that the BCSymbolMaps & dSYMs are properly generated once the `include_debug_symbols` param is explicitly set to `true`?
Eg.
```
create_xcframework(
	workspace: 'Framework.xcworkspace',
	scheme: 'Framework',
	destinations: ['iOS'],
        include_debug_symbols: true,
	xcframework_output_directory: 'output'
)
```

Thanks

**Comment by gdetari** [comment]
Thank you, it does include it properly this way.

**Comment by winkelsdorf** [comment]
Good candidate for the Readme imo
